# Generated by Django 4.2.10 on 2024-04-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(upload_to="media/avatars/"),
        ),
    ]
