# Generated by Django 4.2.10 on 2024-04-05 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="profile",
        ),
    ]
