# Generated by Django 4.2.10 on 2024-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_profile_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("services", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="technician_images/"),
                ),
                ("cv", models.FileField(blank=True, upload_to="technician_cvs/")),
                (
                    "skills",
                    models.ManyToManyField(related_name="technicians", to="main.skill"),
                ),
            ],
        ),
    ]
