# Generated by Django 4.2.10 on 2024-04-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_skill_technician"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="services",
            field=models.ManyToManyField(
                related_name="appointments", to="main.service"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="technical_staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.technician",
            ),
        ),
        migrations.RemoveField(
            model_name="technician",
            name="services",
        ),
        migrations.AddField(
            model_name="technician",
            name="services",
            field=models.ManyToManyField(related_name="technicians", to="main.service"),
        ),
    ]
