# Generated by Django 4.2.10 on 2024-04-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_appointment_services_appointment_technical_staff_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="booking",
            new_name="appointment",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="details",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="title",
        ),
        migrations.AddField(
            model_name="feedback",
            name="message",
            field=models.CharField(default="yes", max_length=255),
        ),
    ]
