# Generated by Django 4.2.10 on 2024-04-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_booking_feedback_appointment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="technician",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.technician",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.CharField(
                choices=[("accept", "Accept"), ("reject", "Reject")],
                default="accept",
                max_length=10,
            ),
        ),
    ]
