# Generated by Django 4.2.10 on 2024-04-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_collaboration_delete_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="technical_staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.technician"
            ),
        ),
    ]
