# Generated by Django 4.2.10 on 2024-04-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_appointment_technical_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("document", models.FileField(blank=True, upload_to="project/")),
            ],
        ),
        migrations.AddField(
            model_name="contract",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="title",
            field=models.CharField(
                choices=[
                    ("IT Support", "IT Support contract"),
                    ("Network Maintenance", "Network Maintenance"),
                    ("Electrical contract", "Electrical contract"),
                    ("Plumbing contract", "Plumbing contract"),
                ],
                max_length=100,
            ),
        ),
    ]
