# Generated by Django 4.2.10 on 2024-05-09 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_contract_technician_name_alter_contract_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactInfo",
        ),
    ]
